"""
SyntheticTicketFactory for generating maintenance tickets from machine failures.
"""
from typing import TYPE_CHECKING, Optional, List
import random

if TYPE_CHECKING:
    from kata.entities.machines.machine import Machine
    from kata.entities.requests.RepairRequest import RepairRequest

from kata.entities.tickets.synthetic_ticket import SyntheticTicket


class SyntheticTicketFactory:
    """
    Factory for generating synthetic maintenance tickets based on machine failures.
    
    This factory creates tickets with realistic field population based on:
    - Machine state and type
    - Component failure information (for ComplexMachine)
    - Buffer states from the SimPy environment
    - Dynamic priority calculation based on failure context
    """
    
    def __init__(
        self,
        priority_rules: Optional[dict] = None,
        add_randomness: bool = False,
        random_priority_variance: int = 0,
        ticket_id_counter: int = 1,
    ) -> None:
        """
        Initialize the SyntheticTicketFactory.
        
        Args:
            priority_rules: Dictionary mapping failure types or component types to base priorities.
                           Example: {"motor": 10, "sensor": 5, "pump": 8}
            add_randomness: Whether to add random variance to generated fields
            random_priority_variance: +/- variance for priority when randomness is enabled
            ticket_id_counter: Starting value for ticket ID generation
        """
        self.priority_rules = priority_rules or {}
        self.add_randomness = add_randomness
        self.random_priority_variance = random_priority_variance
        self._ticket_id_counter = ticket_id_counter
    
    def create_ticket_from_repair_request(
        self,
        repair_request: "RepairRequest",
    ) -> SyntheticTicket:
        """
        Create a synthetic ticket from a repair request.
        
        Args:
            repair_request: The repair request generated by machine failure
            
        Returns:
            SyntheticTicket with populated fields
        """
        machine = repair_request.machine
        
        # Extract machine information
        machine_type = machine.mtype
        
        # Extract component information if available
        component_info = repair_request.get_failed_component_info()
        
        # Determine failure type
        if component_info:
            failure_type = f"component_failure_{component_info['component_type']}"
            component_id = component_info["component_id"]
            component_type = component_info["component_type"]
            repair_time_estimate = component_info["repair_time"]
        else:
            failure_type = "general_failure"
            component_id = None
            component_type = None
            repair_time_estimate = repair_request.get_repair_time()
        
        # Calculate priority
        priority = self._calculate_priority(
            machine=machine,
            failure_type=failure_type,
            component_type=component_type,
        )
        
        # Get buffer level
        nb_in_buffer = self._get_buffer_level(machine)
        
        # Generate ticket ID
        ticket_id = self._generate_ticket_id()
        
        # Create and return ticket
        return SyntheticTicket(
            machine=machine,
            machine_type=machine_type,
            failure_type=failure_type,
            priority=priority,
            nb_in_buffer=nb_in_buffer,
            created_at=repair_request.created_at,
            ticket_id=ticket_id,
            component_id=component_id,
            component_type=component_type,
            repair_time_estimate=repair_time_estimate,
        )
    
    def create_ticket_from_machine(
        self,
        machine: "Machine",
        created_at: int,
    ) -> SyntheticTicket:
        """
        Create a synthetic ticket directly from a machine.
        
        This is useful when you need to generate a ticket without a RepairRequest.
        
        Args:
            machine: The machine that has failed
            created_at: Simulation time when the ticket should be created
            
        Returns:
            SyntheticTicket with populated fields
        """
        # Extract machine information
        machine_type = machine.mtype
        
        # Try to get component information if ComplexMachine
        component_id = None
        component_type = None
        repair_time_estimate = 10.0  # Default
        
        if hasattr(machine, 'get_failed_component'):
            failed_component = machine.get_failed_component()
            if failed_component:
                component_id = failed_component.get_id()
                component_type = failed_component.get_type()
                repair_time_estimate = failed_component.get_repair_time()
                failure_type = f"component_failure_{component_type}"
            else:
                failure_type = "general_failure"
        else:
            failure_type = "general_failure"
        
        # Calculate priority
        priority = self._calculate_priority(
            machine=machine,
            failure_type=failure_type,
            component_type=component_type,
        )
        
        # Get buffer level
        nb_in_buffer = self._get_buffer_level(machine)
        
        # Generate ticket ID
        ticket_id = self._generate_ticket_id()
        
        # Create and return ticket
        return SyntheticTicket(
            machine=machine,
            machine_type=machine_type,
            failure_type=failure_type,
            priority=priority,
            nb_in_buffer=nb_in_buffer,
            created_at=created_at,
            ticket_id=ticket_id,
            component_id=component_id,
            component_type=component_type,
            repair_time_estimate=repair_time_estimate,
        )
    
    def create_batch_tickets(
        self,
        repair_requests: List["RepairRequest"],
    ) -> List[SyntheticTicket]:
        """
        Create multiple tickets from a batch of repair requests.
        
        Args:
            repair_requests: List of repair requests to convert to tickets
            
        Returns:
            List of SyntheticTicket instances
        """
        return [
            self.create_ticket_from_repair_request(req)
            for req in repair_requests
        ]
    
    def _calculate_priority(
        self,
        machine: "Machine",
        failure_type: str,
        component_type: Optional[str] = None,
    ) -> int:
        """
        Calculate priority for a ticket based on failure context.
        
        Priority factors:
        1. Component type (from priority_rules)
        2. Buffer level (higher buffer = higher priority)
        3. Machine utilization (how much it has processed)
        4. Random variance (if enabled)
        
        Args:
            machine: The failed machine
            failure_type: Type of failure
            component_type: Type of component that failed (if applicable)
            
        Returns:
            Priority value (higher = more urgent)
        """
        base_priority = 5  # Default medium priority
        
        # Apply component-specific priority from rules
        if component_type and component_type in self.priority_rules:
            base_priority = self.priority_rules[component_type]
        elif failure_type in self.priority_rules:
            base_priority = self.priority_rules[failure_type]
        
        # Adjust based on buffer level (more items waiting = higher priority)
        buffer_level = self._get_buffer_level(machine)
        if buffer_level > 10:
            base_priority += 3
        elif buffer_level > 5:
            base_priority += 2
        elif buffer_level > 0:
            base_priority += 1
        
        # Adjust based on machine productivity (more productive machines get priority)
        if hasattr(machine, 'total_processed') and machine.total_processed > 100:
            base_priority += 2
        elif hasattr(machine, 'total_processed') and machine.total_processed > 50:
            base_priority += 1
        
        # Add randomness if enabled
        if self.add_randomness and self.random_priority_variance > 0:
            variance = random.randint(-self.random_priority_variance, self.random_priority_variance)
            base_priority += variance
        
        # Ensure priority is at least 1
        return max(1, base_priority)
    
    def _get_buffer_level(self, machine: "Machine") -> int:
        """
        Get the current number of items in the machine's input buffer.
        
        Args:
            machine: The machine to check
            
        Returns:
            Number of items in the input buffer
        """
        if hasattr(machine, 'input_buffer'):
            # For SimPy Store, use len() which accesses items list
            if hasattr(machine.input_buffer, 'items'):
                return len(machine.input_buffer.items)
            # For Buffer wrapper, use __len__
            elif hasattr(machine.input_buffer, '__len__'):
                return len(machine.input_buffer)
        
        return 0
    
    def _generate_ticket_id(self) -> int:
        """
        Generate a unique ticket ID.
        
        Returns:
            Unique ticket ID
        """
        ticket_id = self._ticket_id_counter
        self._ticket_id_counter += 1
        return ticket_id
