"""Compare per-agent wall-clock cost, normalized for episode dynamics.

Raw episode wall time is not comparable across agents: each agent's
actions reshape the episode (number of breakdowns, decisions, repairs),
and horizons differ per scenario.  This script normalizes ``wall_s``
from the benchmark artefacts two ways:

* **ms / decision step** — wall time divided by ``n_steps`` (the number
  of decision points the agent actually faced).  The fair
  compute-cost comparison between policies.
* **s / 1M sim t.u.** — wall time divided by ``final_sim_time``.  The
  cost of simulating a fixed span of factory time with that agent in
  the loop (what a longer-horizon study pays).

Both include the shared SimPy environment cost — the *delta* between
agents is the decision overhead (heuristic arithmetic vs network
forward + probe calls).  All rows of one generation come from the same
machine (v6w: dgy, V100, learned agents on GPU), so ratios are
comparable within a root but not across roots.

Reads ``<root>/<scenario>/episodes.csv`` (same layout as
``analyze_hvp_results.py``), prints per-scenario and pooled tables, and
writes ``wall_time.csv`` + ``wall_time_table.tex`` under ``<root>``.

Usage::

    uv run python scripts/compare_wall_time.py --root reports/hvp_eval_v6w
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from analyze_hvp_results import AGENT_LABELS, AGENT_ORDER, SCENARIOS  # noqa: E402


def load(root: Path) -> pd.DataFrame:
    """Long frame of per-episode normalized costs across scenarios."""
    frames = []
    for scen in SCENARIOS:
        f = root / scen / "episodes.csv"
        if not f.is_file():
            continue
        df = pd.read_csv(f, usecols=["agent", "episode", "wall_s", "n_steps",
                                     "final_sim_time"])
        df["scenario"] = scen
        frames.append(df)
    if not frames:
        raise SystemExit(f"no episodes.csv under {root}")
    df = pd.concat(frames, ignore_index=True)
    df["ms_per_dec"] = df.wall_s / df.n_steps * 1e3
    df["s_per_mtu"] = df.wall_s / df.final_sim_time * 1e6
    return df


def per_scenario(df: pd.DataFrame) -> pd.DataFrame:
    g = (df.groupby(["scenario", "agent"])
           .agg(episodes=("episode", "count"),
                wall_s=("wall_s", "mean"),
                n_steps=("n_steps", "mean"),
                ms_per_dec=("ms_per_dec", "mean"),
                ms_per_dec_std=("ms_per_dec", "std"),
                s_per_mtu=("s_per_mtu", "mean"))
           .reset_index())
    g["ms_per_dec_std"] = g.ms_per_dec_std.fillna(0.0)
    return g


def pooled(df: pd.DataFrame) -> pd.DataFrame:
    """Ratio-of-sums pooling: total wall over total steps (step-weighted,
    robust to the scenario mix in a way mean-of-ratios is not)."""
    g = (df.groupby("agent")
           .agg(episodes=("episode", "count"),
                wall_s=("wall_s", "sum"),
                n_steps=("n_steps", "sum"),
                sim=("final_sim_time", "sum"))
           .reset_index())
    g["ms_per_dec"] = g.wall_s / g.n_steps * 1e3
    g["s_per_mtu"] = g.wall_s / g.sim * 1e6
    return g


def ordered(agents) -> list[str]:
    known = [a for a in AGENT_ORDER if a in agents]
    return known + sorted(set(agents) - set(known))


def print_tables(scen_tab: pd.DataFrame, pool_tab: pd.DataFrame) -> None:
    for scen in [s for s in SCENARIOS if s in set(scen_tab.scenario)]:
        sub = scen_tab[scen_tab.scenario == scen].set_index("agent")
        sub = sub.loc[ordered(sub.index)].sort_values("ms_per_dec")
        print(f"=== {scen} ===")
        print(f"{'agent':<22}{'eps':>4}{'wall s':>9}{'steps':>9}"
              f"{'ms/dec':>9}{'±':>7}{'s/1M t.u.':>11}")
        for a, r in sub.iterrows():
            print(f"{a:<22}{r.episodes:>4.0f}{r.wall_s:>9.1f}{r.n_steps:>9.0f}"
                  f"{r.ms_per_dec:>9.2f}{r.ms_per_dec_std:>7.2f}{r.s_per_mtu:>11.1f}")
        print()
    sub = pool_tab.set_index("agent")
    sub = sub.loc[ordered(sub.index)].sort_values("ms_per_dec")
    print("=== pooled (ratio of sums, all scenarios) ===")
    print(f"{'agent':<22}{'eps':>4}{'ms/dec':>9}{'s/1M t.u.':>11}")
    for a, r in sub.iterrows():
        print(f"{a:<22}{r.episodes:>4.0f}{r.ms_per_dec:>9.2f}{r.s_per_mtu:>11.1f}")


def latex_table(scen_tab: pd.DataFrame, pool_tab: pd.DataFrame) -> str:
    scens = [s for s in SCENARIOS if s in set(scen_tab.scenario)]
    agents = ordered(set(pool_tab.agent))
    heads = {"baseline": "Baseline", "small_scale": "Small",
             "massive_scale": "Industrial", "very_long": "Very long",
             "lifecycle": "Lifecycle"}
    lines = [
        r"% Auto-generated by scripts/compare_wall_time.py — do not edit.",
        r"\begin{tabular}{l" + "r" * (len(scens) + 1) + "}",
        r"\toprule",
        " & ".join(["Agent"] + [heads.get(s, s) for s in scens] + ["Pooled"])
        + r" \\",
        r"\midrule",
    ]
    best = {s: scen_tab[scen_tab.scenario == s].ms_per_dec.min() for s in scens}
    best["__pool"] = pool_tab.ms_per_dec.min()
    for a in agents:
        cells = [AGENT_LABELS.get(a, a.replace("_", r"\_"))]
        for s in scens:
            row = scen_tab[(scen_tab.scenario == s) & (scen_tab.agent == a)]
            if row.empty:
                cells.append("--")
                continue
            v, sd = row.ms_per_dec.iloc[0], row.ms_per_dec_std.iloc[0]
            txt = f"{v:.2f} $\\pm$ {sd:.2f}"
            cells.append(rf"\textbf{{{txt}}}" if v <= best[s] + 1e-9 else txt)
        v = pool_tab[pool_tab.agent == a].ms_per_dec.iloc[0]
        txt = f"{v:.2f}"
        cells.append(rf"\textbf{{{txt}}}" if v <= best["__pool"] + 1e-9 else txt)
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="reports/hvp_eval_v6w",
                    help="benchmark root holding <scenario>/episodes.csv")
    args = ap.parse_args()
    root = Path(args.root)

    df = load(root)
    scen_tab, pool_tab = per_scenario(df), pooled(df)
    print_tables(scen_tab, pool_tab)

    csv_path = root / "wall_time.csv"
    scen_tab.assign(label=scen_tab.agent.map(lambda a: AGENT_LABELS.get(a, a))
                    ).to_csv(csv_path, index=False)
    tex_path = root / "wall_time_table.tex"
    tex_path.write_text(latex_table(scen_tab, pool_tab))
    print(f"\nwrote {csv_path} and {tex_path}  (ms/dec, mean ± std over episodes;"
          " pooled = ratio of sums)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
